In [1]:
import numpy as np

In [2]:
angka = [1,2,3,4]

In [3]:
angkanp = np.array(angka)

In [4]:
angkanp

array([1, 2, 3, 4])

In [5]:
angka*3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [6]:
# kita ingin angka yang di list dikalikan 3 satu-satu

angkanp*3

array([ 3,  6,  9, 12])

In [8]:
versilist = [[1,2,3],[4,5,6],[7,8,9]]
versilist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
# kita buat dua dimensi dengan cara

versinumpy = np.array(versilist)
versinumpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange (0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [12]:
# nilainya null semua

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,4)) #hasilnya akan dua dimensi

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
# nilainya angka satu semua

np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((2,4)) #hasilnya akan dua dimensi

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.linspace (0,8,10)

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

**Identity Matrix**

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])