In [15]:
import numpy as np

In [16]:
# bilangan distribusi uniform (0-1)

np.random.rand(7) #bilangan random 7 list

array([0.62145478, 0.93180133, 0.3683911 , 0.03344113, 0.61924157,
       0.79949862, 0.24279062])

In [17]:
# bilangan distribusi uniform (0-1) matriks dua dimensi

np.random.rand(5,4)

array([[0.58885814, 0.42909117, 0.55548163, 0.54350304],
       [0.87940099, 0.28964915, 0.50120118, 0.42604704],
       [0.49400207, 0.37296248, 0.25558756, 0.26839237],
       [0.27964674, 0.3162291 , 0.07406649, 0.92246512],
       [0.66662205, 0.98297645, 0.70520722, 0.51101099]])

In [18]:
# distribusi normal (gaussian) angkanya tidak lagi 0-1 melainkan minus (-) tak hingga sampi plus (+) tak hingga

np.random.randn(10)

array([ 1.90766814, -0.72446307, -0.18869831,  1.21030175,  0.04522266,
        0.93487766, -0.08311853,  0.49473814,  0.44678763, -1.3261697 ])

In [19]:
# distribusi normal (gaussian) matriks dua dimensi

np.random.randn(4,4)

array([[ 0.71343929,  0.58155417, -1.07342103,  1.56715894],
       [ 0.31831913, -1.19968689,  2.45776316, -0.77423726],
       [-0.58671067, -0.05894615, -0.4429161 ,  1.53356668],
       [-0.43945574,  2.26399083, -0.93868477,  1.16357706]])

In [20]:
# ada cara cepat agar tidak terlalu panjang

from numpy.random import randn

In [21]:
randn(6,2)

array([[ 0.35278583,  0.02050464],
       [-0.29141732,  0.68063802],
       [-1.3237619 , -0.84019147],
       [ 0.59019744, -0.61687342],
       [-1.07191364,  0.45719011],
       [ 0.38989933,  0.92060242]])

In [22]:
from numpy.random import rand

In [23]:
randn(3,4)

array([[ 0.74976671, -0.36474426,  1.37921738,  0.58316481],
       [-1.49685246, -0.51352208,  1.11267023, -1.81219717],
       [ 1.37676135,  1.43104529, -0.22762528,  1.6241492 ]])

In [24]:
from numpy.random import randn, randint #mengenerate sebuah integer

In [25]:
randint(0,10)

6

In [26]:
randint(0,10,5) # butuh 5 angka integer dari bilangan 0 - 10

array([2, 3, 7, 3, 9])

In [27]:
bilangan = randint (0,100,20) # butuh 20 angka integer dari bilangan 0 - 100

In [28]:
bilangan

array([70, 41, 34, 84,  4, 90, 60, 57, 61, 31, 29, 16, 95, 46, 27, 63, 25,
       25, 36, 82])

In [29]:
bilangan.reshape(2,10) # mengkalikan dua dimensi

array([[70, 41, 34, 84,  4, 90, 60, 57, 61, 31],
       [29, 16, 95, 46, 27, 63, 25, 25, 36, 82]])

In [30]:
from numpy.random import rand, randn, randint

In [31]:
randint (0,3,5) #maka angka 3 tidak diikutkan karena slicing

array([0, 2, 2, 0, 1])

In [32]:
randint (0,10,25)

array([3, 8, 3, 1, 5, 6, 1, 5, 4, 3, 1, 2, 8, 3, 3, 5, 2, 4, 9, 8, 1, 0,
       8, 3, 5])

In [33]:
coba = randint (0,10,20).reshape(5,4)
coba

array([[5, 2, 3, 5],
       [2, 5, 2, 5],
       [3, 2, 9, 7],
       [0, 0, 6, 4],
       [2, 4, 3, 2]])

In [34]:
coba.reshape(2,10)

array([[5, 2, 3, 5, 2, 5, 2, 5, 3, 2],
       [9, 7, 0, 0, 6, 4, 2, 4, 3, 2]])

In [35]:
coba = coba.reshape(2,10)

In [36]:
coba

array([[5, 2, 3, 5, 2, 5, 2, 5, 3, 2],
       [9, 7, 0, 0, 6, 4, 2, 4, 3, 2]])

In [37]:
from numpy.random import rand, randn, randint

In [38]:
# membuat satu dimensi dengan dua dimensi

coba1d = randint (0,100,20) #ini satu dimensi

In [39]:
coba2d = randint (0,100,20).reshape(4,5) #ini dua dimensi

In [40]:
coba1d

array([32, 58, 59, 43, 35, 14, 17, 75, 88, 13, 82, 26, 56, 82, 86, 69, 44,
       51, 21, 24])

In [41]:
coba2d

array([[ 9, 91, 74, 81, 66],
       [95, 87, 27, 87, 19],
       [63, 75, 95, 44,  6],
       [ 8, 57, 39, 52, 21]])

In [42]:
coba1d.max() #melihat nilai terbesar dari 1 dimensi

88

In [43]:
coba2d.max() #melihat nilai terbesar dari 2 dimensi

95

In [44]:
coba1d.min() #melihat nilai terkecil dari 1 dimensi

13

In [45]:
coba2d.min() #melihat nilai terkecil dari 2 dimensi

6

In [46]:
coba1d.argmax () #melihat indeks keberapa nilai terbesar dari dimensi 1

8

In [47]:
coba2d.argmax ()

5

In [48]:
coba1d.argmin () #melihat indeks keberapa nilai terkecil dari dimensi 1

9

In [49]:
coba2d.argmin ()

14

In [49]:
# perlu diperhatikan penggunaan argmax dan agrmin akan sangat berguna di AI dan data science

In [50]:
coba1d.shape #agar tahu dimensi array/matriks kita seperti apa

(20,)

In [51]:
coba2d.shape

(4, 5)

In [52]:
coba1d.dtype

dtype('int32')

# Indexing di Numpy

In [53]:
import numpy as np

In [56]:
coba = np.arange(0,11)
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
coba [7]

7

In [58]:
coba[5:]

array([ 5,  6,  7,  8,  9, 10])

In [59]:
coba[5:9]

array([5, 6, 7, 8])

In [60]:
coba[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [62]:
coba2 = coba [:6]
coba2

array([0, 1, 2, 3, 4, 5])

In [63]:
coba2 [:] = 100
coba2    # di numpy jika kita otak-atik coba2 maka akan berpengaruh pada coba

array([100, 100, 100, 100, 100, 100])

In [64]:
coba

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [65]:
# bagaimana jika coba2 ingin berdiri sendiri yitu dengan copy
coba2 = coba.copy()

In [67]:
coba2 [:] = 200
coba2

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [68]:
coba

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [69]:
bil2d = np.array ([[1,2,3],[4,5,6],[7,8,9]])
bil2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
# jika ingin mengambil angka 1 maka tuliskan baris ke berapa diikuti kolom keberapa

bil2d [0][0]

1

In [71]:
bil2d[1]

array([4, 5, 6])

In [72]:
bil2d[2][2]

9

In [73]:
# cara yang direkomendasikan
bil2d [2,2]

9

In [74]:
bil2d[0,0]

1

In [75]:
bil2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
bil2d[1:2,1:] #jika kita ingin mengambil angka 5 dan 6

array([[5, 6]])

**Slicing dengan boolean di Numpy**

In [77]:
import numpy as pd

In [80]:
bil = np.arange(1,11)
bil

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
angkaT = bil>5
angkaT

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [82]:
bil = bil [angkaT] # karena ini bersifat True maka angka yang ditampilkan adalah yang >5 = True
bil

array([ 6,  7,  8,  9, 10])

In [83]:
# cara yang lebih simple

bil = np.arange(1,11)
bil

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
bil[bil>5]

array([ 6,  7,  8,  9, 10])

In [85]:
bil2 = bil[bil>5]
bil2

array([ 6,  7,  8,  9, 10])