**Operasi di Numpy**

In [1]:
import numpy as np

In [3]:
coba = np.arange (0,11)
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
coba+5 #jika seperti ini maka dijumlahkan satu per satu

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
coba+coba #sama halnya seperti diatas

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
#jika ingin berbeda

coba_list = [0,1,2,3,4,5,6,7,8,9,10]

In [7]:
coba_list+coba_list #maka akan dijumlahkan secara keseluruhan

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
coba*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
coba_list*3

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10]

In [10]:
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
coba-coba

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
coba-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [13]:
1/0

ZeroDivisionError: division by zero

In [14]:
coba/coba #numpy akan tetap mencoba memberikan ouput namun memberikan warning

C:\Users\HP\AppData\Local\Temp\ipykernel_12096\3645045052.py:1: RuntimeWarning: invalid value encountered in divide
  coba/coba


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [15]:
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
1/coba

C:\Users\HP\AppData\Local\Temp\ipykernel_12096\379956285.py:1: RuntimeWarning: divide by zero encountered in divide
  1/coba


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [17]:
np.sqrt(coba) #menggunakan akar

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [18]:
#nilai eksponensial (e pangkat n) e = 2.7182

np.exp(coba)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [20]:
#mencari nilai max
np.max(coba)

10

In [21]:
coba.max()

10

In [22]:
np.min(coba)

0

In [23]:
# merubah menjadi sin

np.sin(coba)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [24]:
np.log(coba) #menggunakan logaritmik

C:\Users\HP\AppData\Local\Temp\ipykernel_12096\1831656404.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(coba) #menggunakan logaritmik


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])